# Для развертывания собственных контейнеров на платформе L!vestack вам необходимо:
# убедиться, что в корне вашего проекта есть Dockerfile. Если его нет, создайте и настройте в соответствии с требованиями вашего приложения.
# https://docs.docker.com/reference/dockerfile/
# собрать Docker-образ.
# https://docs.docker.com/reference/cli/docker/buildx/imagetools/create/
# запушить образ в ghcr или в другой приватный Registry.
# вставить ссылку на образ в конфигурационный файл развертывания.
# прописать  username и password (токен) в конфигурационный файл развертывания.
# ==========================================================
# Детальные инструкции доступны по ссылке:
# https://github.com/H3LLO-CLOUD/l1vestack-examples
# ==========================================================

services:
  app:

  # Запускаемый образ
  # https://docs.docker.com/reference/compose-file/services/#image
    image: ghcr.io/h3llo-cloud/example:latest # public image for examples

  # Передача в окружение порта
  # Документация: https://docs.docker.com/reference/cli/docker/container/port/

    environment:
      - PORT=80

  # Установка порта, для доступа из внутренней сети проекта
  # http://app:80
  # https://docs.docker.com/reference/compose-file/services/#ports
    ports:
      - "80:80"

  # Подключение Private Docker Registry
  # Детальная инструкция по созданию токена по ссылке:
  # https://github.com/H3LLO-CLOUD/l1vestack-examples
x-registry:
  "ghcr.io":
    username: "your username by Githab"
    password: "your token for ghcr"
