services:
  app:
    depends_on:
      postgres:
        condition: service_healthy
    image: svhd/logto
    entrypoint: ["sh", "-c", "npm install -g @logto/cli && logto db alt deploy --target-version <версия> && npm run cli db seed -- --swe && npm start"]
    ports:
      - 3001:3001
      - 3002:3002
    environment:
      - TRUST_PROXY_HEADER=1
      - DB_URL=postgresql://postgres:p0stgr3s@postgres:5432/logto
      - REDIS_URL=redis://redis:6379
      - ENDPOINT
      - ADMIN_ENDPOINT
    networks:
      - app-network

  postgres:
    image: postgres:17-alpine
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p0stgr3s
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge