# Сервис MariaDB - альтернатива MySQL
services: # (Оставьте этот блок только в первом контейнере, в последующих – подключайтесь к уже запущенному сервису)
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: example
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    volumes:
      - ./mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"              # Порт MariaDb (не рекомендуется открывать публичный доступ)

  # Опционально: сервис adminer для быстрого доступа к БД
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"                  # Доступ к adminer по адресу http://localhost:8080
