services:
  tiddlywiki:
    image: mazzolino/tiddlywiki
    container_name: tiddlywiki
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./tiddlywiki:/var/lib/tiddlywiki


#  Auth
#  Default auth is user / wiki
#
#  Simply provide the USERNAME and PASSWORD env variables to customise.
#
#  Other settings
#  If you are in a memory-constrained environment, you can provide the NODE_MEM environment variable to specify the memory ceiling (in MB)
#
# To serve the tiddlywiki at a non-root prefix path set the SERVE_URI environment variable: this variable ''must'' start with a forward slash character.
# The tiddlywiki will be served by the container at http:///${SERVE_URI} - the container initialization script takes care of setting the required host configuration tiddler.