services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      PGDATA: /var/lib/postgresql/data  # Указание вложенной директории
    volumes:
      - zabbix-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    restart: always
    depends_on:
      - db
    environment:
      DB_SERVER_HOST: db
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    ports:
      - "10051:10051"

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    restart: always
    depends_on:
      - db
      - zabbix-server
    environment:
      DB_SERVER_HOST: db
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: Europe/Moscow  # Установи свой часовой пояс
    ports:
      - "8080:8080"  # Веб-интерфейс Zabbix
      - "8443:8443"  # HTTPS, если нужен

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    restart: always
    depends_on:
      - zabbix-server
    environment:
      ZBX_SERVER_HOST: zabbix-server
    ports:
      - "10050:10050"


#Login    Admin
#Password: zabbix