services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5439:5432"

  gotrue:
    image: supabase/gotrue:v2.10.1
    depends_on:
      - db
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://postgres:postgres@db:5432/postgres?sslmode=disable
      #jdbc:postgresql://postgres:5432/keycloak
      GOTRUE_SITE_URL: http://localhost:3000
      GOTRUE_JWT_SECRET: your-secret-key
      GOTRUE_JWT_EXP: 3600
      GOTRUE_OPERATOR_TOKEN: your-operator-token
    ports:
      - "9999:9999"

volumes:
  db_data:
