services: # (Оставьте этот блок только в первом контейнере, в последующих – подключайтесь к уже запущенному сервису)
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres   # Логин для подключения к базе данных
      POSTGRES_DB: postgres     # Имя основной базы данных
      POSTGRES_PASSWORD: password  # Пароль для пользователя postgres
      PGDATA: /var/lib/postgresql/data/data  # Путь для хранения данных внутри контейнера (обязательно для l1vestack)

    volumes:
      - ./pg_data:/var/lib/postgresql/data  # Локальная папка для хранения данных PostgreSQL (сохранение при перезапуске - обязательно для l1vestack)

    ports:
      - "5432:5432"  # Открытие порта PostgreSQL (обязательно для l1vestack - не рекомендуется подключать публичный адрес )`,

  # Опционально: сервис adminer для быстрого доступа к БД
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"                  # Доступ к adminer по адресу http://localhost:8080