global:
  scrape_interval: 15s  # Как часто опрашивать таргеты (по умолчанию 1m)
  evaluation_interval: 15s  # Как часто переоценивать правила (если есть alerting)

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
