#-----------------------------------------------------
# Конфигурация всегда начинается с services:
# При вставке второго и последующего сниппета  данную строку удалить во избежание ошибки
#-----------------------------------------------------

services: #удалить во втором и последующих контейнерах
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres   # Логин для подключения к базе данных
      POSTGRES_DB: postgres     # Имя основной базы данных
      POSTGRES_PASSWORD: password  # Пароль для пользователя postgres
      PGDATA: /var/lib/postgresql/data/data  # Путь для хранения данных внутри контейнера (обязательно для l1vestack)

    volumes:
      - ./pg_data:/var/lib/postgresql/data  # Локальная папка для хранения данных PostgreSQL (сохранение при перезапуске - обязательно для l1vestack)

    ports:
      - "5432:5432"  # Открытие порта PostgreSQL ( обязательно для l1vestack - не рекомендуется подключать публичный адрес )