services:
  db:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gitea
      POSTGRES_PASSWORD: giteapass
      POSTGRES_DB: gitea


  gitea:
    image: gitea/gitea:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "3000:3000"  # Web UI
      - "222:22"     # SSH
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=giteapass
      - SSH_PORT=222
      - GITEA__server__DOMAIN=localhost
      - GITEA__server__SSH_PORT=222
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=giteapass