services:

  db:
    image: mariadb:latest
    container_name: espocrm-db
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: myrootpassword
      MARIADB_DATABASE: espocrm
      MARIADB_USER: espocrm
      MARIADB_PASSWORD: mypassword
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - espocrm-network

  espocrm:
    image: espocrm/espocrm:latest
    container_name: espocrm
    restart: always
    environment:
      ESPOCRM_DATABASE_HOST: db
      ESPOCRM_DATABASE_USER: espocrm
      ESPOCRM_DATABASE_PASSWORD: mypassword
      ESPOCRM_ADMIN_USERNAME: admin
      ESPOCRM_ADMIN_PASSWORD: admin123
    depends_on:
      - db
    volumes:
      - ./crm_data:/var/www/html
    ports:
      - "8080:80"
    networks:
      - espocrm-network

volumes:
  db_data:
  crm_data:

networks:
  espocrm-network:
    driver: bridge
